# Generated by Django 4.2.4 on 2023-08-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpCode', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=100)),
                ('Desg', models.CharField(max_length=50)),
                ('Gradepay', models.CharField(max_length=50)),
                ('Age', models.CharField(max_length=50)),
                ('Emailid', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('officeaddr', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('projectno', models.CharField(max_length=50)),
                ('rs', models.CharField(max_length=50)),
            ],
        ),
    ]
